  const words = [
    "about", "above", "actor", "acute", "admit", "adopt", "adult", "after", "again", "agent",
    "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along",
    "alter", "among", "angle", "angry", "apart", "apple", "apply", "arena", "argue", "arise",
    "array", "aside", "asset", "audio", "audit", "avoid", "await", "award", "aware", "awful",
    "badly", "basic", "basis", "batch", "begin", "being", "below", "bench", "birth", "black",
    "blade", "blame", "blank", "blast", "blend", "blind", "block", "blood", "board", "boost",
    "booth", "bound", "brand", "bread", "break", "brief", "bring", "broad", "brown", "brush",
    "build", "buyer", "cable", "calm", "carry", "catch", "cause", "chain", "chair", "chart",
    "chase", "cheap", "check", "chest", "chief", "child", "claim", "class", "clean", "clear",
    "clock", "close", "coach", "coast", "count", "court", "cover", "crack", "craft", "crash",
    "crazy", "cream", "crime", "cross", "crowd", "crown", "curve", "cycle", "daily", "dance",
    "dated", "dealt", "death", "debut", "delay", "depth", "doing", "doubt", "dozen", "draft",
    "drama", "drawn", "dream", "dress", "drift", "drink", "drive", "drove", "dying", "eager",
    "early", "earth", "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal",
    "error", "event", "every", "exact", "exist", "extra", "faith", "false", "fault", "favor",
    "fence", "fetch", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flash",
    "fleet", "floor", "fluid", "focus", "force", "forth", "found", "frame", "frank", "fraud",
    "fresh", "front", "fruit", "fully", "funny", "giant", "given", "glass", "globe", "going",
    "grace", "grade", "grand", "grant", "grass", "great", "green", "gross", "group", "guard",
    "guess", "guest", "guide", "habit", "happy", "hardy", "harry", "heart", "heavy", "hello",
    "hence", "honor", "horse", "hotel", "house", "human", "ideal", "image", "index", "inner",
    "input", "issue", "items", "joint", "judge", "known", "label", "large", "laser", "later",
    "laugh", "layer", "learn", "least", "leave", "legal", "level", "light", "limit", "links",
    "lives", "local", "logic", "loose", "lower", "lucky", "lunch", "lying", "magic", "major",
    "maker", "march", "match", "maybe", "mayor", "meant", "media", "metal", "meter", "might",
    "minor", "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth", "movie",
    "music", "needs", "never", "newly", "night", "noise", "north", "notes", "novel", "nurse",
    "occur", "ocean", "offer", "often", "order", "other", "ought", "outer", "owner", "panel",
    "paper", "party", "patch", "pause", "peace", "phase", "phone", "photo", "piece", "pilot",
    "pitch", "place", "plain", "plane", "plant", "plate", "point", "power", "press", "price",
    "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove", "quick", "quiet",
    "quite", "radio", "raise", "range", "rapid", "ratio", "reach", "ready", "realm", "reply",
    "reset", "ridge", "right", "rigid", "risen", "river", "rough", "round", "route", "royal",
    "rural", "scale", "scene", "scope", "score", "sense", "serve", "setup", "seven", "shall",
    "shape", "share", "sharp", "sheep", "shift", "shirt", "shock", "shoot", "short", "shown",
    "sight", "since", "sixth", "sixty", "sized", "skill", "sleep", "slice", "slide", "small",
    "smart", "smell", "smile", "smoke", "solid", "solve", "sorry", "sound", "south", "space",
    "spare", "speak", "speed", "spend", "split", "spoke", "sport", "staff", "stage", "stake",
    "stand", "start", "state", "stats", "steal", "stick", "still", "stock", "stone", "store",
    "storm", "story", "strip", "study", "stuff", "style", "sugar", "suite", "super", "sweet",
    "swing", "table", "taken", "taste", "taxes", "teach", "teeth", "terms", "thank", "their",
    "theme", "there", "these", "thick", "thing", "think", "third", "those", "three", "throw",
    "tight", "times", "today", "topic", "total", "touch", "tough", "tower", "track", "trade",
    "train", "treat", "trend", "trial", "troop", "truck", "truly", "trust", "truth", "twice",
    "under", "union", "unity", "until", "upper", "urban", "usage", "usual", "valid", "value",
    "video", "views", "virus", "visit", "vital", "voice", "voter", "waste", "watch", "water",
    "weigh", "weird", "wheel", "where", "which", "while", "white", "whole", "whose", "wider",
    "width", "woman", "wonder", "words", "world", "worry", "worth", "would", "write", "wrong",
    "wrote", "yield", "young", "yours",
  ];

function get_random_word() {
    return words[Math.floor(Math.random() * 100)];
}